<?php

// In config/courses.php
return [
    'courses' => [
        ''                                => '—Please choose an option—',
        'AutoCAD 2D Professional'         => 'AutoCAD 2D Professional',
        'AutoCAD 2D Expert'               => 'AutoCAD 2D Expert',
        'AutoCAD 3D'                      => 'AutoCAD 3D',
        'Mastering AutoCAD'               => 'Mastering AutoCAD',
        'Revit Architecture Professional' => 'Revit Architecture Professional',
        'Revit Architecture Expert'       => 'Revit Architecture Expert',
        'Sketch up'                       => 'Sketch up',
        '3Ds MAX Architecture'            => '3Ds MAX Architecture',
        'Coloring Manual Presentation'    => 'Coloring Manual Presentation',
        'Photoshop Architecture'          => 'Photoshop Architecture',
        'Rhinoceros &Grasshopper'         => 'Rhinoceros &Grasshopper',
        'Ecotect Analysis'                => 'Ecotect Analysis',
        'CSI Diploma'                     => 'CSI Diploma',
        'Robot Analysis'                  => 'Robot Analysis',
        'Sap'                             => 'Sap',
        'AutoCAD Structure Detailing'     => 'AutoCAD Structure Detailing',
        'AutoCAD Civil 3D Professional'   => 'AutoCAD Civil 3D Professional',
        'AutoCAD Civil 3D Expert'         => 'AutoCAD Civil 3D Expert',
        'Infrastrucrure Diploma'          => 'Infrastrucrure Diploma',
        'Primavera Level 1'               => 'Primavera Level 1',
        'Primavera Level 2'               => 'Primavera Level 2',
        'Navisworks'                      => 'Navisworks',
        'PMP'                             => 'PMP',
        'Architecutural Finishing'        => 'Architecutural Finishing',
        'Revit MEP Professional'          => 'Revit MEP Professional',
        'Revit MEP Expert'                => 'Revit MEP Expert',
        'Inventor Professioanl'           => 'Inventor Professioanl',
        'Inventor Expert'                 => 'Inventor Expert',
        'Solidworks Professional'         => 'Solidworks Professional',
        'Solidworks Expert'               => 'Solidworks Expert',
        'Gaphics Design Principles'       => 'Gaphics Design Principles',
        'Graphics Diploma'                => 'Graphics Diploma',
        'Motion Graphics Diploma'         => 'Motion Graphics Diploma',
        'Final Cut Diploma'               => 'Final Cut Diploma',
        'Web Design Diploma'              => 'Web Design Diploma',
        'Photoshop'                       => 'Photoshop',
        'Illustrator'                     => 'Illustrator',
        'InDesign'                        => 'InDesign',
    ],
];
